(in-package #:aoc2021)

(defun day15-gold-parse (file)
  (make-gold-risk-matrix (make-risk-matrix file)))

(defun day15-gold (risk-matrix)
  (let* ((adjacencies (make-adjacency-hash risk-matrix))
         (matrix-size (array-total-size risk-matrix))
         (visits (make-array (array-dimensions risk-matrix) :element-type 'bit))
         (prevs  (make-array (array-dimensions risk-matrix) :element-type '(unsigned-byte 32)))
         (acosts (make-array (array-dimensions risk-matrix) :element-type '(unsigned-byte 32) :initial-element 4294967295))
         (costs  (make-gold-costs matrix-size)))
    (print matrix-size)
    (dijkstra-gold (1- matrix-size) risk-matrix
                   adjacencies visits prevs costs acosts)
    (+ (retrace-and-sum (1- matrix-size) risk-matrix prevs)
       (row-major-aref risk-matrix (1- matrix-size)))))

(defun dijkstra-gold (to matrix adjacencies visits prevs costs acosts)
  (iter (for (node . cost) = (heap-extract-maximum costs))
    (while (and node (/= node to)))
    (dolist (adj (href adjacencies node))
      (let ((new-cost (+ cost (row-major-aref matrix adj))))
        (when (and (not (logbitp 0 (row-major-aref visits adj)))
                   (< new-cost (row-major-aref acosts adj)))
          (setf (row-major-aref prevs adj) node)
          (setf (row-major-aref acosts adj) new-cost)
          (heap-insert costs `(,adj . ,new-cost)))))
    (setf (row-major-aref visits node) #b1)))

(defun make-gold-costs (size)
  (lret ((heap (make-heap :key #'cdr :test #'<=)))
    (iter (for i :from 1 :below size)
      (heap-insert heap `(,i . ,most-positive-fixnum)))
    (heap-insert heap (cons 0 0))))

(defun make-gold-risk-matrix (matrix)
  (destructuring-bind (ncols nrows) (array-dimensions matrix)
    (lret ((5-matrix
            (make-array (mapcar (op (* 5 _)) `(,ncols ,nrows))
                        :element-type '(unsigned-byte 4))))
      ;; Horizontal Grids
      (dotimes (y ncols)
        (dotimes (x nrows)
          (setf (aref 5-matrix x y) (aref matrix x y))
          (dotimes (dt 4)
            (let ((curry (+ y (*     dt  ncols)))
                  (nexty (+ y (* (1+ dt) ncols))))
              (setf (aref 5-matrix x nexty)
                    (1+ (mod (aref 5-matrix x curry) 9)))))))
      ;; Vertical Grids
      (dotimes (y (array-dimension 5-matrix 1))
        (dotimes (x nrows)
          (dotimes (dt 4)
            (let ((currx (+ x (*     dt  ncols)))
                  (nextx (+ x (* (1+ dt) ncols))))
              (setf (aref 5-matrix nextx y)
                    (1+ (mod (aref 5-matrix currx y) 9))))))))))
