name: CI
on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.org'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: clfoundation/sbcl:2.1.11
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        env:
          cache-name: cache-alpine
        with:
          path: |
            ~/quicklisp/
            ~/.cache/common-lisp/
          key: "${{ env.cache-name }}-${{ github.sha }}"
          restore-keys: "${{ env.cache-name }}"

      - run: /usr/local/bin/install-quicklisp
        if: hashFiles('~/quicklisp/setup.lisp') != ''

      - name: Deps not on Quicklisp
        run: |
          cd ~/quicklisp/
          test -d trivialtests || git clone --depth=1 https://github.com/eigenhombre/trivialtests.git
          test -d cl-oju       || git clone --depth=1 https://github.com/eigenhombre/cl-oju.git
          (cd trivialtests/ && git pull )
          (cd cl-oju/       && git pull )

      - name: Run tests
        run: |
          sbcl --non-interactive --no-sysinit --no-userinit \
               --load ~/quicklisp/setup.lisp \
               --load aoc2021.asd \
               -e "(asdf:test-system :aoc2021)"
