name: Build aoc2021

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.org'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 40ants/setup-lisp@v1
        with:
          asdf-system: aoc2021
      - uses: 40ants/run-tests@v2
        with:
          asdf-system: aoc2021
